CREATE TABLE [dbo].[ABM_KEY_Assignment] (
    [Delmodel]                 NVARCHAR (64) NOT NULL,
    [Period]                   NVARCHAR (64) NOT NULL,
    [Scenario]                 NVARCHAR (64) NOT NULL,
    [SourceModuleType]         NVARCHAR (64) NULL,
    [SourceReference]          NVARCHAR (64) NOT NULL,
    [DestinationModuleType]    NVARCHAR (64) NULL,
    [DestinationReference]     NVARCHAR (64) NOT NULL,
    [DriverName]               NVARCHAR (64) NULL,
    [DriverQuantityFixed]      FLOAT (53)    NULL,
    [DriverQuantityVariable]   FLOAT (53)    NULL,
    [DriverWeightFixed]        FLOAT (53)    NULL,
    [DriverWeightVariable]     FLOAT (53)    NULL,
    [SourceDimRef1]            NVARCHAR (64) NULL,
    [SourceDimMemberRef1]      NVARCHAR (64) NULL,
    [SourceDimRef2]            NVARCHAR (64) NULL,
    [SourceDimMemberRef2]      NVARCHAR (64) NULL,
    [SourceDimRef3]            NVARCHAR (64) NULL,
    [SourceDimMemberRef3]      NVARCHAR (64) NULL,
    [SourceDimRef4]            NVARCHAR (64) NULL,
    [SourceDimMemberRef4]      NVARCHAR (64) NULL,
    [SourceDimRef5]            NVARCHAR (64) NULL,
    [SourceDimMemberRef5]      NVARCHAR (64) NULL,
    [DestinationDimRef1]       NVARCHAR (64) NULL,
    [DestinationDimMemberRef1] NVARCHAR (64) NULL,
    [DestinationDimRef2]       NVARCHAR (64) NULL,
    [DestinationDimMemberRef2] NVARCHAR (64) NULL,
    [DestinationDimRef3]       NVARCHAR (64) NULL,
    [DestinationDimMemberRef3] NVARCHAR (64) NULL,
    [DestinationDimRef4]       NVARCHAR (64) NULL,
    [DestinationDimMemberRef4] NVARCHAR (64) NULL,
    [DestinationDimRef5]       NVARCHAR (64) NULL,
    [DestinationDimMemberRef5] NVARCHAR (64) NULL,
    CONSTRAINT [PK_ABM_KEY_Assignment] PRIMARY KEY CLUSTERED ([Delmodel] ASC, [Period] ASC, [Scenario] ASC, [SourceReference] ASC, [DestinationReference] ASC) WITH (FILLFACTOR = 90)
);

