CREATE TABLE [edw].[Omsaetningstal] (
    [LitraGr]           VARCHAR (15)    NULL,
    [FraTil_Tid1]       VARCHAR (13)    NULL,
    [PrPrimo_Vaerdi_SP] DECIMAL (38, 3) NULL,
    [F_lp_Vaerdi_SP]    DECIMAL (38, 3) NULL,
    [I_lp_Vaerdi_SP]    DECIMAL (38, 3) NULL,
    [A_lp_Vaerdi_SP]    DECIMAL (38, 3) NULL,
    [R_lp_Vaerdi_SP]    DECIMAL (38, 3) NULL,
    [T_lp_Vaerdi_SP]    DECIMAL (38, 3) NULL,
    [Afst_lp_Vd_SP]     DECIMAL (38, 3) NULL,
    [OmsHast1_Vd]       DECIMAL (38, 6) NULL,
    [FraTil_Tid2]       VARCHAR (13)    NULL,
    [Primo_Vaerdi_SP]   DECIMAL (38, 3) NULL,
    [F_cp_Vaerdi_SP]    DECIMAL (38, 3) NULL,
    [I_cp_Vaerdi_SP]    DECIMAL (38, 3) NULL,
    [A_cp_Vaerdi_SP]    DECIMAL (38, 3) NULL,
    [R_cp_Vaerdi_SP]    DECIMAL (38, 3) NULL,
    [T_cp_Vaerdi_SP]    DECIMAL (38, 3) NULL,
    [Afstem_cp_Vd_SP]   DECIMAL (38, 3) NULL,
    [Ult_Vaerdi_SP]     DECIMAL (38, 3) NULL,
    [OmsHast2_Vd]       DECIMAL (38, 6) NULL,
    [F_index_Vd]        DECIMAL (38, 6) NULL,
    [I_index_Vd]        DECIMAL (38, 6) NULL,
    [OH_index_Vd]       DECIMAL (38, 6) NULL,
    [PrPrimo_Beh]       DECIMAL (38, 3) NULL,
    [F_lp_Maengde]      DECIMAL (38, 3) NULL,
    [I_lp_Maengde]      DECIMAL (38, 3) NULL,
    [A_lp_Maengde]      DECIMAL (38, 3) NULL,
    [R_lp_Maengde]      DECIMAL (38, 3) NULL,
    [T_lp_Maengde]      DECIMAL (38, 3) NULL,
    [Afstem_lp_Mgd]     DECIMAL (38, 3) NULL,
    [OmsHast1_Mgd]      DECIMAL (38, 6) NULL,
    [Primo_Beh]         DECIMAL (38, 3) NULL,
    [F_cp_Maengde]      DECIMAL (38, 3) NULL,
    [I_cp_Maengde]      DECIMAL (38, 3) NULL,
    [A_cp_Maengde]      DECIMAL (38, 3) NULL,
    [R_cp_Maengde]      DECIMAL (38, 3) NULL,
    [T_cp_Maengde]      DECIMAL (38, 3) NULL,
    [Afstem_cp_Mgd]     DECIMAL (38, 3) NULL,
    [Ultimo_Beh]        DECIMAL (38, 3) NULL,
    [OmsHast2_Mgd]      DECIMAL (38, 6) NULL,
    [F_index_Mgd]       DECIMAL (38, 6) NULL,
    [I_index_Mgd]       DECIMAL (38, 6) NULL,
    [OH_index_Mgd]      DECIMAL (38, 6) NULL
);

