CREATE TABLE [edw].[PeriodeAnalyse_Brutto] (
    [FraTil_Tid]      VARCHAR (13)     NULL,
    [Dim_F]           VARCHAR (10)     NULL,
    [Dim_M]           INT              NULL,
    [Dim_FM]          INT              NULL,
    [Materiale]       VARCHAR (18)     NULL,
    [MaterialeTekst]  VARCHAR (50)     NULL,
    [ONr]             INT              NULL,
    [Dim_Aendr_Navn]  VARCHAR (20)     NULL,
    [LNType]          VARCHAR (4)      NULL,
    [FLNType]         VARCHAR (4)      NULL,
    [LitraGr2]        VARCHAR (15)     NULL,
    [StatusGr2]       VARCHAR (20)     NULL,
    [Beh_N]           DECIMAL (18, 3)  NOT NULL,
    [Beh_F]           DECIMAL (18, 3)  NOT NULL,
    [Delta_Beh]       DECIMAL (19, 3)  NULL,
    [Ansk_Vd_N]       DECIMAL (18, 3)  NOT NULL,
    [Ansk_Vd_F]       DECIMAL (18, 3)  NOT NULL,
    [Delta_Vd]        DECIMAL (19, 3)  NULL,
    [NedskrNetto_N]   DECIMAL (18, 3)  NOT NULL,
    [NedskrNetto_F]   DECIMAL (18, 3)  NOT NULL,
    [Delta_Nedskr]    DECIMAL (19, 3)  NULL,
    [NedForPrinc]     DECIMAL (18, 3)  NOT NULL,
    [DSystAnedr]      DECIMAL (18, 3)  NOT NULL,
    [DUF_N]           INT              NULL,
    [DUF_F]           INT              NULL,
    [D_DUF]           INT              NULL,
    [RID_N]           INT              NULL,
    [RID_F]           INT              NULL,
    [D_RID]           INT              NULL,
    [Vaerdi_SP_N]     DECIMAL (18, 3)  NOT NULL,
    [Vaerdi_SP_F]     DECIMAL (18, 3)  NOT NULL,
    [Delta_SP]        DECIMAL (19, 3)  NULL,
    [Forskel]         DECIMAL (18, 3)  NOT NULL,
    [NytMatKorr]      DECIMAL (18, 3)  NOT NULL,
    [IndkLgVaerdi]    DECIMAL (18, 3)  NOT NULL,
    [IndkLgKorr]      DECIMAL (18, 3)  NOT NULL,
    [N_Pct]           DECIMAL (7, 5)   NOT NULL,
    [SN_Pct]          DECIMAL (7, 5)   NOT NULL,
    [LaN_Pct]         DECIMAL (7, 5)   NOT NULL,
    [RN_Pct]          DECIMAL (7, 5)   NOT NULL,
    [LiN_Pct]         DECIMAL (7, 5)   NOT NULL,
    [MRPcontr]        VARCHAR (10)     NULL,
    [MRP_type]        VARCHAR (10)     NULL,
    [ABC_IN]          VARCHAR (10)     NULL,
    [IKGruppe]        VARCHAR (10)     NULL,
    [VareGrp]         VARCHAR (20)     NULL,
    [F_N]             TINYINT          NULL,
    [F_I]             TINYINT          NULL,
    [F_U]             TINYINT          NULL,
    [FTrMd]           VARCHAR (7)      NULL,
    [P_DUF]           INT              NULL,
    [DUF_N_Aar]       INT              NULL,
    [P_Pct]           DECIMAL (9, 7)   NULL,
    [P0_Brutto]       DECIMAL (28, 10) NULL,
    [NytMatMgd]       DECIMAL (18, 3)  NULL,
    [NytMatVaerdi]    DECIMAL (18, 3)  NULL,
    [IndkLgMgd]       DECIMAL (18, 3)  NULL,
    [P1_NytMatMgd]    DECIMAL (18, 3)  NULL,
    [P1_NytMatVaerdi] DECIMAL (18, 3)  NULL,
    [P1_NytMatKorr]   DECIMAL (26, 8)  NULL
);

