CREATE TABLE [edw].[TD02_Klass_MatLitra] (
    [Materiale] VARCHAR (9)  NULL,
    [BR]        VARCHAR (15) NULL,
    [DOB]       VARCHAR (15) NULL,
    [EA]        VARCHAR (15) NULL,
    [EG]        VARCHAR (15) NULL,
    [ETS]       VARCHAR (15) NULL,
    [FLS]       VARCHAR (15) NULL,
    [GVG]       VARCHAR (15) NULL,
    [IC2]       VARCHAR (15) NULL,
    [IC3]       VARCHAR (15) NULL,
    [IC4]       VARCHAR (15) NULL,
    [IR4]       VARCHAR (15) NULL,
    [KOF]       VARCHAR (15) NULL,
    [ME]        VARCHAR (15) NULL,
    [MET]       VARCHAR (15) NULL,
    [MK]        VARCHAR (15) NULL,
    [MQ]        VARCHAR (15) NULL,
    [MR]        VARCHAR (15) NULL,
    [PRO]       VARCHAR (15) NULL,
    [S1]        VARCHAR (15) NULL,
    [ST4]       VARCHAR (15) NULL,
    [UDR]       VARCHAR (15) NULL,
    [OST]       VARCHAR (15) NULL,
    [XYZ]       VARCHAR (15) NULL
);

