CREATE TABLE [ods].[RD_Togproduktion_Tog] (
    [Dato]                    DATETIME        NULL,
    [AarMaaned]               VARCHAR (50)    NULL,
    [Togsysnr]                VARCHAR (50)    NULL,
    [Togsysnavn]              VARCHAR (50)    NULL,
    [Togsysforkortelse]       VARCHAR (50)    NULL,
    [ICStraekning]            VARCHAR (50)    NULL,
    [Togkategori]             VARCHAR (50)    NULL,
    [Togkategoribeskrivelse]  VARCHAR (50)    NULL,
    [Togkategoriejer]         VARCHAR (50)    NULL,
    [Tognr]                   INT             NULL,
    [TognrInterval]           VARCHAR (50)    NULL,
    [Fratidspunkt]            VARCHAR (50)    NULL,
    [Tiltidspunkt]            VARCHAR (50)    NULL,
    [Frastation]              VARCHAR (50)    NULL,
    [Tilstation]              VARCHAR (50)    NULL,
    [Traekkraft]              VARCHAR (50)    NULL,
    [Antaltraekkrafter]       INT             NULL,
    [AntalVogne]              INT             NULL,
    [Loebestrk]               VARCHAR (100)   NULL,
    [RetningsbestemtStrk]     VARCHAR (100)   NULL,
    [IkkeRetningsbestemtStrk] VARCHAR (100)   NULL,
    [Omraade]                 VARCHAR (50)    NULL,
    [Omraadeland]             VARCHAR (50)    NULL,
    [Division]                VARCHAR (50)    NULL,
    [Produkt]                 VARCHAR (50)    NULL,
    [Kontraktoperatoer]       VARCHAR (50)    NULL,
    [Tekniskoperatoer]        VARCHAR (50)    NULL,
    [erSaertog]               BIT             NULL,
    [erOmlagt]                BIT             NULL,
    [erMaterielkoersel]       BIT             NULL,
    [erTomkoersel]            BIT             NULL,
    [erEkstraproduktion]      BIT             NULL,
    [erTogdublering]          BIT             NULL,
    [erAflyst]                BIT             NULL,
    [Togkm]                   DECIMAL (24, 6) NULL,
    [Togminutter]             BIGINT          NULL,
    [Status]                  VARCHAR (50)    NULL,
    [Timestamp]               DATETIME        NULL
);

