CREATE TABLE [ods].[td0_CD_G_ETL5_Ressourceportal_Anlæg] (
    [HovednrUnr]            VARCHAR (50) NULL,
    [AktiverDato]           DATETIME     NULL,
    [BetegnelseAnlaegAktiv] VARCHAR (50) NULL,
    [Balkonto]              VARCHAR (50) NULL,
    [AnlKlasse]             VARCHAR (50) NULL,
    [AkkAfskrPrimo]         FLOAT (53)   NULL,
    [AkkAfskrUltimo]        FLOAT (53)   NULL,
    [Afskrivning]           FLOAT (53)   NULL,
    [BogfoertVaerdiPrimo]   FLOAT (53)   NULL,
    [BogfoertVaerdiUltimo]  FLOAT (53)   NULL,
    [OmkStedUltimo]         VARCHAR (50) NULL,
    [OmkStedNavnUltimo]     VARCHAR (50) NULL,
    [Sats]                  FLOAT (53)   NULL,
    [AnskVaerdi]            FLOAT (53)   NULL,
    [Profitcenter]          VARCHAR (50) NULL,
    [AfskrivningerAM]       FLOAT (53)   NULL,
    [Afvigelse]             FLOAT (53)   NULL,
    [Forrentningsgrundlag]  FLOAT (53)   NULL,
    [Forrentning]           FLOAT (53)   NULL,
    [Kilde_Beskrivelse]     VARCHAR (50) NULL,
    [costpool]              VARCHAR (50) NULL,
    [Reference_ID]          VARCHAR (55) NULL,
    [Niveau]                VARCHAR (50) NULL,
    [Sort]                  INT          NULL,
    [Reference_Name]        VARCHAR (50) NULL,
    [Reference_Parent]      VARCHAR (50) NULL,
    [Reference_Name_Parent] VARCHAR (50) NULL,
    [Type]                  VARCHAR (50) NULL,
    [EvenlyAssigned]        VARCHAR (50) NULL,
    [DriverName]            VARCHAR (50) NULL,
    [Model]                 VARCHAR (50) NULL,
    [Aktiv]                 VARCHAR (50) NULL,
    [Ressource_Beskrivelse] VARCHAR (50) NULL,
    [ATT_ResType]           VARCHAR (50) NULL,
    [Periode]               VARCHAR (50) NULL,
    [KildeArk]              VARCHAR (50) NULL
);

