CREATE TABLE [edw].[FT_Togproduktion_Tog] (
    [FK_DI_Tid]                  VARCHAR (50)    NOT NULL,
    [FK_DI_Togsystem]            INT             NOT NULL,
    [Togkategori]                VARCHAR (50)    NULL,
    [Togkategoribeskrivelse]     VARCHAR (50)    NULL,
    [Togkategoriejer]            VARCHAR (50)    NULL,
    [Tognr]                      INT             NULL,
    [TognrInterval]              VARCHAR (50)    NULL,
    [Fratidspunkt]               VARCHAR (50)    NULL,
    [Tiltidspunkt]               VARCHAR (50)    NULL,
    [Frastation]                 VARCHAR (50)    NULL,
    [Tilstation]                 VARCHAR (50)    NULL,
    [Traekkraft]                 VARCHAR (50)    NULL,
    [Antaltraekkrafter]          INT             NULL,
    [AntalVogne]                 INT             NULL,
    [Loebestrk]                  VARCHAR (100)   NULL,
    [RetningsbestemtStrk]        VARCHAR (100)   NULL,
    [IkkeRetningsbestemtStrk]    VARCHAR (100)   NULL,
    [Omraade]                    VARCHAR (50)    NULL,
    [Omraadeland]                VARCHAR (50)    NULL,
    [Division]                   VARCHAR (50)    NULL,
    [Kontraktoperatoer]          VARCHAR (50)    NULL,
    [Tekniskoperatoer]           VARCHAR (50)    NULL,
    [erSaertog]                  BIT             NULL,
    [erOmlagt]                   BIT             NULL,
    [erMaterielkoersel]          BIT             NULL,
    [erTomkoersel]               BIT             NULL,
    [erEkstraproduktion]         BIT             NULL,
    [erTogdublering]             BIT             NULL,
    [erAflyst]                   BIT             NULL,
    [Togkm]                      DECIMAL (24, 6) NULL,
    [Togminutter]                DECIMAL (24, 6) NULL,
    [Status]                     VARCHAR (50)    NULL,
    [Timestamp]                  DATETIME        NULL,
    [FraTime]                    INT             NULL,
    [TilTime]                    INT             NULL,
    [FK_DI_Tidsintervaller]      INT             NULL,
    [erTrafikkontraktProduktion] BIT             DEFAULT ((0)) NULL,
    CONSTRAINT [FK_FT_Togproduktion_Tog_DI_Tid] FOREIGN KEY ([FK_DI_Tid]) REFERENCES [edw].[DI_Tid] ([Reference]),
    CONSTRAINT [FK_FT_Togproduktion_Tog_DI_Tidsintervaller] FOREIGN KEY ([FK_DI_Tidsintervaller]) REFERENCES [edw].[DI_Tidsintervaller] ([PK_ID]),
    CONSTRAINT [FK_FT_Togproduktion_Tog_DI_Togsystem] FOREIGN KEY ([FK_DI_Togsystem]) REFERENCES [edw].[DI_Togsystem] ([PK_DI_Togsystem])
);

